### ISSUE TITLE
Prompt Before package install --- Feature request

### ISSUE THREAD

**Issue by skirankumar7** [webpack-contrib/install-webpack-plugin#129]
Issue Type: 
**Request Feature**

**Current Flow:** 
As an when the user typed new package in source code plugin checks if plugin installed or not if not present install plugin and compile

**Problem with current Flow:** 
If the user mistakenly gave another package name (some spelling mistakes) or missed **/** to append or prepend then that package is installing.

**Proposed solution:** 
Before installing package prompt user in the console/ command prompt that is this the correct package you want to install if user confirms install it else compile without installing that package.

Thanks...

**Comment by anikethsaha** [comment]
having prompt every time will slow down everything even the web packs compilation.  
This plugin solves the issue of not opening a terminal and installing each package. So if prompted then the purpose of this plugin won't be applied.

I am 👎 for this 
@evilebottnawi thoughts?

**Comment by evilebottnawi** [comment]
I think it is good for option (by default `false`)

**Comment by anikethsaha** [comment]
I am afraid it will make the development should.

> I think it is good for option (by default `false`)

yeah.

**Comment by alexander-akait** [comment]
Fixed
