### ISSUE TITLE
Prefix for own logging

### ISSUE THREAD

**Issue by insin** [webpack-contrib/install-webpack-plugin#94]
What do you think of prefixing the plugin's own logging with `"[NpmInstallPlugin] "` or similar so it's clear where it's coming from?

**Comment by ericclemmons** [comment]
That'd be great.  I've personally used `debug` since it seems ubiquitous.

**Comment by insin** [comment]
We could have default and make it configurable.

From the perspective of integrating `NpmInstallPlugin` into toolkits, its output logging becomes part of your UI, which is the primary reason for this and a quiet flag.
